services:
  spark:
    image: apache/spark:3.5.1
    container_name: spark-shell
    ports:
      - "4040:4040"   # Spark app UI
      - "8085:8080"   # Spark Master UI
      - "7078:7077"   # Spark Master port
    volumes:
      - ./data:/data
    command: /bin/bash
    stdin_open: true
    tty: true
